### ISSUE TITLE
Kostra knihovny, návrh rozhraní pro načtení vstupů

### ISSUE THREAD

**Issue by MartinUbl** [LenticularSoftworks/lenticulis-support#1]
Je třeba připravit základ knihovny, navrhnout komunikační rozhraní pro vstupy, a exportovat vhodné funkce.

V návrhu je třeba dbát na požadavky, a na předběžný návrh fungování. Prozatím bude vhodné detailně navrhnout vstupní operace, které souvisejí s načtením obrázku a jeho předáním do GUI.

Z GUI přijde požadavek na načtení jednoho obrázku (v jeden čas). Tento požadavek je třeba zpracovat tak, aby:
    a. v případě úspěchu byl do GUI poskytnut obrázek komprimovaný (mipmapa), a byly připojeny údaje o rozměrech, DPI, formátu, barevném modelu
    b. v případě neúspěchu byl do GUI odeslán stav, na základě kterého je možné rozpoznat, co je špatně (nepodporovaný formát, chyba v souboru, neexistující soubor, ..)

Tento úkol momentálně nezahrnuje implementaci, ale je vhodné vytvořit kód, který bude tento návrh reflektovat, a bude připraven na implementaci.

**Comment by hermandavid** [comment]
Knihovna bude rozdělena na tři hlavní části. 
První z nich bude služba pro registraci obrázků, která bude zajišťovat přiřazení identifikátoru, uložení klíčových atributů a vytvoření mipmapy, aby nebylo třeba držet v paměti původní obrázek.
Druhá část bude zajiovat jednotlivé operace s obrázky, včetně jejich exportování.
Poslední část bude zajišťovat hromadné operace.
